version: "3.9"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kirribot
      MYSQL_USER: pythonbot
      MYSQL_PASSWORD: Jasmin080914!
    ports:
      - "3307:3306"  # Port nach außen, intern bleibt 3306
    volumes:
      - mysql_data:/var/lib/mysql

  kirribot:
    build: .
    container_name: kirribot
    restart: always
    depends_on:
      - mysql_db
    env_file: .env
    command: ["python", "main.py"]

volumes:
  mysql_data:
