# Basis-Image
FROM python:3.11-slim

# Arbeitsverzeichnis
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Projektdateien kopieren
COPY . .

# Der Dashboard-Service wird über 'command' in docker-compose gestartet: ["python", "dashboard_main.py"]
# EXPOSE ist nicht zwingend notwendig, da der Port in docker-compose unter 'ports' definiert wird
EXPOSE 8000